name: Pulumi
description: A Buildkite plugin that installs and configures Pulumi
author: https://github.com/buildkite
requirements:
  - curl
  - bash
  - jq
configuration:
  properties:
    version:
      type: string
    backend-url:
      type: string
    use-oidc:
      type: boolean
    audience:
      type: string
    pulumi-token-type:
      type: string
    pulumi-token-scope:
      type: string
