name: Pulumi
description: A Buildkite plugin that installs and configures Pulumi
author: https://github.com/buildkite
requirements:
  - curl
  - bash
  - jq
configuration:
  properties:
    version:
      type: string
    backend_url:
      type: string
    use_oidc:
      type: boolean
    audience:
      type: string
    pulumi_token_type:
      type: string
    pulumi_token_scope:
      type: string
