steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**

  - label: ":sparkles:"
    plugins:
      - plugin-linter#v3.3.0:
          id: docker
